version: "2"
run:
  concurrency: 4
  tests: true
linters:
  default: all
  disable:
    - depguard
    - exhaustruct
    - nlreturn
    - tagliatelle
    - varnamelen
    - wrapcheck
    - noinlineerr
    - wsl
    - wsl_v5
  settings:
    funlen:
      statements: 45
    lll:
      line-length: 300
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
    rules:
      - path: library/utils/
        linters:
          - revive
        text: "var-naming"
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
